# -*- coding: utf-8 -*-
"""
BHIV HR Platform - Manual Testing Guide
What you can check manually to validate the workflow
"""

def print_manual_testing_guide():
    print("BHIV HR Platform - Manual Testing Guide")
    print("=" * 60)
    print()
    
    print("1. PORTAL ACCESSIBILITY TEST")
    print("-" * 30)
    print("Open these URLs in your browser:")
    print("  HR Portal: https://bhiv-hr-portal-u670.onrender.com")
    print("  Client Portal: https://bhiv-hr-client-portal-3iod.onrender.com")
    print("  Candidate Portal: https://bhiv-hr-candidate-portal-abe6.onrender.com")
    print("  LangGraph Service: https://bhiv-hr-langgraph.onrender.com")
    print()
    print("Expected: All should load without errors")
    print()
    
    print("2. API DOCUMENTATION TEST")
    print("-" * 30)
    print("Check API documentation:")
    print("  Gateway API: https://bhiv-hr-gateway-ltg0.onrender.com/docs")
    print("  Agent API: https://bhiv-hr-agent-nhgg.onrender.com/docs")
    print("  LangGraph API: https://bhiv-hr-langgraph.onrender.com/docs")
    print()
    print("Expected: Swagger/OpenAPI documentation should load")
    print()
    
    print("3. CLIENT PORTAL WORKFLOW TEST")
    print("-" * 30)
    print("Steps to test job posting:")
    print("  1. Go to: https://bhiv-hr-client-portal-3iod.onrender.com")
    print("  2. Login with credentials: shashankmishra0411@gmail.com / 9284967526")
    print("  3. Navigate to 'Post Job' or 'Create Job' section")
    print("  4. Fill out job details:")
    print("     - Title: 'Test Python Developer Position'")
    print("     - Description: 'Test job for workflow validation'")
    print("     - Requirements: 'Python, FastAPI, PostgreSQL'")
    print("     - Location: 'Remote'")
    print("  5. Submit the job posting")
    print()
    print("Expected: Job should be created successfully")
    print()
    
    print("4. CANDIDATE PORTAL WORKFLOW TEST")
    print("-" * 30)
    print("Steps to test candidate application:")
    print("  1. Go to: https://bhiv-hr-candidate-portal-abe6.onrender.com")
    print("  2. Register/Login with:")
    print("     - Email: shashankmishra0411@gmail.com")
    print("     - Phone: 9284967526")
    print("  3. Browse available jobs")
    print("  4. Apply to the job you created in step 3")
    print("  5. Fill application form with:")
    print("     - Cover letter: 'Test application for workflow validation'")
    print("     - Skills: 'Python, FastAPI, PostgreSQL, Docker'")
    print("  6. Submit application")
    print()
    print("Expected: Application should be submitted successfully")
    print()
    
    print("5. HR PORTAL WORKFLOW TEST")
    print("-" * 30)
    print("Steps to test HR updates:")
    print("  1. Go to: https://bhiv-hr-portal-u670.onrender.com")
    print("  2. Login with credentials: shashankmishra0411@gmail.com / 9284967526")
    print("  3. Navigate to 'Applications' or 'Candidates' section")
    print("  4. Find the application you submitted in step 4")
    print("  5. Update application status to 'Interview Scheduled'")
    print("  6. Add notes: 'Candidate looks promising, scheduling interview'")
    print("  7. Save changes")
    print()
    print("Expected: Status should update and trigger notifications")
    print()
    
    print("6. LANGGRAPH AUTOMATION TEST")
    print("-" * 30)
    print("Steps to verify automation:")
    print("  1. After updating status in step 5, check:")
    print("     - Email notifications (check shashankmishra0411@gmail.com)")
    print("     - WhatsApp messages (check phone 9284967526)")
    print("     - System logs in HR portal")
    print("  2. Go to: https://bhiv-hr-langgraph.onrender.com/docs")
    print("  3. Check available endpoints:")
    print("     - /health (should return 200)")
    print("     - /workflows (check workflow status)")
    print("     - /notifications (check notification history)")
    print()
    print("Expected: Notifications should be sent automatically")
    print()
    
    print("QUICK API TEST COMMANDS:")
    print("You can also test APIs directly:")
    print("  # Test Gateway Health")
    print("  curl -X GET https://bhiv-hr-gateway-ltg0.onrender.com/health")
    print("  # Test LangGraph Health")
    print("  curl -X GET https://bhiv-hr-langgraph.onrender.com/health")
    print("  # Test Agent Health")
    print("  curl -X GET https://bhiv-hr-agent-nhgg.onrender.com/health")
    print()
    
    print("7. API HEALTH CHECK")
    print("-" * 30)
    print("Use curl or browser to check:")
    print("  curl https://bhiv-hr-gateway-ltg0.onrender.com/health")
    print("  curl https://bhiv-hr-agent-nhgg.onrender.com/health")
    print("  curl https://bhiv-hr-langgraph.onrender.com/health")
    print()
    print("Expected: All should return 200 OK with health status")
    print()
    
    print("8. TROUBLESHOOTING TIPS")
    print("-" * 30)
    print("If services are slow or unresponsive:")
    print("  - Render free tier services sleep after 15 minutes of inactivity")
    print("  - First request may take 30-60 seconds to wake up")
    print("  - Refresh the page if it doesn't load immediately")
    print("  - Check browser console for JavaScript errors")
    print("  - Try incognito/private browsing mode")
    print()
    
    print("9. EXPECTED WORKFLOW SEQUENCE")
    print("-" * 30)
    print("Complete workflow should be:")
    print("  Client Portal -> Job Posted -> Database Updated")
    print("  Candidate Portal -> Application Submitted -> Database Updated")
    print("  HR Portal -> Status Changed -> Database Updated")
    print("  LangGraph -> Notifications Sent -> Email/WhatsApp/Telegram")
    print()
    
    print("10. SUCCESS INDICATORS")
    print("-" * 30)
    print("Workflow is working if you see:")
    print("  [OK] All portals load without errors")
    print("  [OK] Job can be posted via Client Portal")
    print("  [OK] Application can be submitted via Candidate Portal")
    print("  [OK] Status can be updated via HR Portal")
    print("  [OK] Notifications are sent when status changes")
    print("  [OK] LangGraph service responds to API calls")
    print()
    
    print("=" * 60)
    print("For automated testing, run: python test_workflow.py")
    print("=" * 60)

if __name__ == "__main__":
    print_manual_testing_guide()